### ISSUE TITLE
"Possessive constructions" (p. 21) and scene-evoking participant nominals

### ISSUE THREAD

**Issue by nschneid** [UniversalConceptualCognitiveAnnotation/docs#4]
We were a bit confused by some of the policies for possessives:

1. Pet ownership is analyzed the same way as ownership of other concrete entities, right? If so I recommend combining them under the first bullet point.

2. "social and personal relationships (the participant himself should be marked P/S)": 

   - Why mark the participant with `P`/`S` and not `A`? It seems (as with the concrete ownership cases) the possessive is marking that there is a relation, and the two NPs (the possessive one and its governor) refer to the two arguments of the relation. The only difference here is that we can infer the specific nature of the relation (such as friendship vs. boss/subordinate) from the governing NP.

   - How is `P` vs. `S` determined? I don't see the motivation for `P` in in "My **friend** is relocating" and "John 's **boss** wasn't at work today.

3. It would be helpful to have additional examples of other kinds of relations that can be expressed possessively here. E.g., alternating with "tip of the iceberg", how should "the iceberg 's tip" and "the iceberg tip" be treated?

**Comment by omriabnd** [comment]
1.

   Pet ownership is analyzed the same way as ownership of other concrete
   entities, right? If so I recommend combining them under the first bullet
   point.

I think this makes sense.


   1.

   "social and personal relationships (the participant himself should be
   marked P/S)":
   -

      Why mark the participant with P/S and not A? It seems (as with the
      concrete ownership cases) the possessive is marking that there is a
      relation, and the two NPs (the possessive one and its governor) refer to
      the two arguments of the relation. The only difference here is
that we can
      infer the specific nature of the relation (such as friendship vs.
      boss/subordinate) from the governing NP.

What do you think of having the possessive marker ("of"/"'s") as the . In
languages where the possession is marked in the morphology (as is sometimes
the case in Hebrew כסאי, רכבך) we will mark it as S+A.


   -

      How is P vs. S determined? I don't see the motivation for P in in "My
      *friend* is relocating" and "John 's *boss* wasn't at work today.

It is not. The only reason for it is UI purposes. We couldn''t find an
intuitive name for their supercategory.


   1.

   It would be helpful to have additional examples of other kinds of
   relations that can be expressed possessively here. E.g., alternating with
   "tip of the iceberg", how should "the iceberg 's tip" and "the iceberg tip"
   be treated?

all the same way. yeah, it would be nice to have such an example.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/UniversalConceptualCognitiveAnnotation/docs/issues/4>,
or mute the thread

**Comment by nschneid** [comment]
> What do you think of having the possessive marker ("of"/"'s") as the . In languages where the possession is marked in the morphology (as is sometimes the case in Hebrew כסאי, רכבך) we will mark it as S+A.

Not sure I understand the suggestion, but I think social relations could be treated like other alienable relations, i.e.:

John_A 's_S boss_A

my_S+A boss_A

Since these are stative relationships between people, I definitely think S makes more sense than P.

For e.g. מנהלנו ('our director'), both sides of the possessive relation are expressed in the word, so unless the pronominal suffix is tokenized separately, the possession wouldn't be annotated, right?

**Comment by omriabnd** [comment]
Sorry. This was an email to Dotan. She'll work on this Wednesday.

**Comment by dotdv** [comment]
I think the decision to mark social relationships as P/S and then specifically as P is based on a different section p.19: 
_**More generally, words that derive a participant from a scene are treated as scenes.
1. “[taxiA driversP ]A areF usuallyD oldS”
2. “[participantsP ]A areF welcomeS”**_

I think I would clarify the phrasing of the above section, but essentially because of it we internally mark all position-holders as P. 
considering this, it made sense that if for example in the case of 'John's boss', we anyhow refer to 'boss' as a Process, and since 'boss' does reflect the type of relation to John, it's better to mark 'boss' as the P.

**Comment by nschneid** [comment]
In "the driver hit a pedestrian", would "driver" and "pedestrian" both evoke scenes?

**Comment by dotdv** [comment]
Yes I think so.

**Comment by nschneid** [comment]
OK—what about "character" (in a story), "chapter" (in a book), or "menu" (of a restaurant, as in "I liked the extensive menu")? All of these imply some larger structure, so are they scene-evoking? They would be in frame semantics, but I gather UCCA's notion of scene is narrower.

**Comment by nschneid** [comment]
Then could the principle be:
- nouns which denote a participant by virtue of being currently, previously, or habitually involved in a certain kind of **activity/profession** ("teacher", "professor", "author", "therapist", "retiree", "rabbi", "pedestrian") evoke a P scene of performing that activity/profession
   * only human/animate?
- nouns denoting an individual (human/animate?) participant of a **kinship relation** or **static social or organizational relationship** ("father", "friend", "boss", "employee", "chairman") should evoke an S scene of the relationship
   * If used in a possessive construction, the possessive marker is R
      - John_A 's_R father_S+A
      - my_A+R father_S+A
      - John_A has_R no_D father_S+A
- unless the noun is used as a title, like Chairman Mao, Prof. Smith, or Father Smith (priest)

**Comment by omriabnd** [comment]
Nice.

On Sat, Sep 15, 2018 at 7:06 PM Nathan Schneider <notifications@github.com>
wrote:

> Then could the principle be:
>
>    - nouns which denote a participant by virtue of being currently,
>    previously, or habitually involved in a certain kind of
>    *activity/profession* ("teacher", "professor", "author", "therapist",
>    "retiree", "rabbi", "pedestrian") evoke a P scene of performing that
>    activity/profession
>       - only human/animate?
>
> Well, in principle no, but I think it's going to be much harder for
annotators if we don't exclude inanimates. We were discussing "bridge" at
some point. I find it hard to believe annotators would see it as a Scene
(I'm talking about an actual bridge).

**Comment by nschneid** [comment]
Or "ingredients" (I'm annotating a recipe at the moment.) Agreed, I bet annotators would have trouble identifying inanimate scene-evokers.

**Comment by nschneid** [comment]
If we go with the above modification to the guidelines I think we have possession of concrete entities (including pets) as the only case where the possessive construction evokes a scene. What about more abstract relations like "John's name/height/idea/future"—does the noun evoke a scene? Or are all non-concrete possessions considered inalienable? Or should the possessive construction also evoke a scene here?

**Comment by omriabnd** [comment]
"John's name": not a Scene.
height / idea / future : Scene

**Comment by nschneid** [comment]
Proposal:

Concrete constitutive relations (Part-Whole, Component Material) should not evoke scenes.

Otherwise, either the head noun evokes a scene, or the possessive construction within an E evokes a scene. The possessive construction evoking a scene applies to abstract possession as well as concrete alienable possession.

[John_A 's_S (dog)_A]_E dog_C
[John_A 's_S (name)_A]_E name/address_C

**Comment by omriabnd** [comment]
Proposal:

**Step 1:** Decide if the main noun is Scene-evoking
if yes: clear what to do

if no: decide whether the E is an E Scene or not (several options here)
Add here the instruction that possession of non-concrete head nouns should always be counted as non-inherent, so evoking an E Scene

**Comment by nschneid** [comment]
Regarding whether the above policy for "actor", "father", "pedestrian" etc. should be limited to humans or animates, consider also:

"predators and their prey"

"a can opener" (i.e. a device designed to open cans)

**Comment by jakpra** [comment]
> [John_A 's_S (dog)_A]_E dog_C
> [John_A 's_S (name)_A]_E name/address_C
> John_A 's_R father_S+A

Does this scale well to of-possessives?
the_E dog_C [(dog)_A of_S John_A]_E
the_E father_S+A of_R John_A

Or should we stick with the more "conservative" version?
the_E dog_C of_R John_E
the_E father_C of_R John_E


> John_A has_R no_D father_S+A

Should "has" really be treated as R? I see the intuition that "father" should be treated consistently as S (if at all), but this would lead to a dramatic exception in the treatment of verbs, and will also create an anomaly in the UCCA-SNACS extension (because we don't have PPS for "have").

**Comment by nschneid** [comment]
Responding to @jakpra:

* Possessives evoking scenes—should this also apply to "of"? I'm not sure. Will leave this up to @omriabnd and @dotdv to clarify. (Personally, I'm not entirely sure why alienability should matter in determining whether the possessive evokes a scene. Maybe there should be no scene unless evoked by the head noun.)

* > John_A 's_R father_S+A...violates the general rule that R shouldn't be a sibling of P/S.
    
   You're right. I guess R should always be within an A unless it is relating a C and an E (or two Cs).

* "John has no father": Yeah, it would be odd to have a verb as R. Maybe it should be considered a light verb, i.e. F.

For the record, I don't have particularly strong opinions on the treatment of possessives—I'm mainly trying to clarify the boundaries between the cases and to make sure the system is internally consistent.

**Comment by nschneid** [comment]
Is a brave soul willing to draft new possessive guidelines in a Google doc so we can discuss there? This thread is long enough that it's hard to keep track of the latest decisions.

**Comment by dotdv** [comment]
> "John has no father": Yeah, it would be odd to have a verb as R. Maybe it should be considered a light verb, i.e. F.  

Yes, the "possessive have" section p.25 in the guidelines refers to this, it says: 

Whenever ``have''  carries the semantic meaning of ownership 
and precedes a concrete object (e.g. book, pen), it should be marked an S.
``John_A has_S [a book]_A'' 

But whenever ``have'' is part of a phrase describing an action or event,  then it should be marked as a light verb. 
John_A [had_F a_E walk_C]_P yesterday_T''
John_A [has_F problems_C]_S
John_A [has_F hobbies_C]_S
 
*As a side note maybe it will be better if we slightly rephrase/simplify the distinction to be between cases where the unit that follows the possessive have is evoking/not evoking a scene.
But in any case, regarding your example, since 'father' wasn't scene-evoking until now I think maybe we'd annotate it: "John_A does_F n't_D have_S [a_E father_C]_A", but if we indeed regard 'father' as S+A, then yes I think it makes sense to annotate 'have' as a light verb: John doesn't [have_F a_E father_C]_S+(A?)

**Comment by dotdv** [comment]
> Is a brave soul willing to draft new possessive guidelines in a Google doc so we can discuss there? This thread is long enough that it's hard to keep track of the latest decisions.

@omriabnd  let me know if you would like my help rewriting any issue or if you prefer to write yourself. Waiting for your call

**Comment by dotdv** [comment]
I added a new section under "Classification of Possessives" and disabled the previous possessive constructions section. Omri, I think I pretty much followed the titles you wrote down. I hope it reflects our discussion. 
More examples can definitely be added but I think that first it will help if we resolve and update these issues in the guidelines: part-whole, partitives, participant nominals. 

Suggestion:  under "Classification of possessives" we can have two sections: one about possessive constructions (which already exists), and one that we can add about possession verbs to which we can move the "possessive have" section from where it is now.  It might help clarify how these are treated differently, no?

**Comment by nschneid** [comment]
Thanks @dotdv, this is a great start! 

(From now on, could you log into Overleaf before editing? It is showing these changes as by Anonymous.)

I've added another example ("my car") and a couple of comments.

> Suggestion: under "Classification of possessives" we can have two sections: one about possessive constructions (which already exists), and one that we can add about possession verbs to which we can move the "possessive have" section from where it is now. It might help clarify how these are treated differently, no?

Agreed—it makes sense to take about "of", "'s", and "have" together. Maybe the prepositions section can be merged with the possessives section.

**Comment by omriabnd** [comment]
On Wed, 17 Oct 2018, 16:51 Nathan Schneider, <notifications@github.com>
wrote:

> Thanks @dotdv <https://github.com/dotdv>, this is a great start!
>
> (From now on, could you log into Overleaf before editing? It is showing
> these changes as by Anonymous.)
>
> I've added another example ("my car") and a couple of comments.
>
> Suggestion: under "Classification of possessives" we can have two
> sections: one about possessive constructions (which already exists), and
> one that we can add about possession verbs to which we can move the
> "possessive have" section from where it is now. It might help clarify how
> these are treated differently, no?
>
> Agreed—it makes sense to take about "of", "'s", and "have" together. Maybe
> the prepositions section can be merged with the possessives section.
>
I agree

**Comment by dotdv** [comment]
@nschneid yes right, I'll make sure to sign in Overleaf
